[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "index.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/*"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/images/*"
  Content-Type = "image/jpeg"
  Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  Content-Type = "application/javascript"
